### ISSUE TITLE
How to set swfPath

### ISSUE THREAD

**Issue by robdecker** [zeroclipboard/jquery.zeroclipboard#3]
When using the regular ZeroClipboard library, I can do something like this:

`ZeroClipboard.config({swfPath: '/a/path/to/zeroclipboard/dist/ZeroClipboard.swf'});`

How do I do that with jquery.zeroclipboard?

**Comment by vanderlee** [comment]
Had the same issue. Your solution works for me.
Perhaps it would be handy to include it in the documentation or the Github wiki.
